CREATE TABLE "PRODUIT" (	
    "ID_PRODUIT" NUMBER(10) NOT NULL ENABLE,
    "CODART" CHAR(4) NOT NULL ENABLE, 
	"LIBART" CHAR(30 CHAR) NOT NULL ENABLE, 
	"STKALE" NUMBER(7,0) NOT NULL ENABLE, 
	"STKPHY" NUMBER(7,0) NOT NULL ENABLE, 
	"QTEANN" NUMBER(7,0) NOT NULL ENABLE, 
	"UNIMES" CHAR(6 CHAR) NOT NULL ENABLE
);


CREATE TABLE "FOURNISSEUR" (	
    "ID_FOURNISSEUR" NUMBER(10) NOT NULL ENABLE,
    "NUMFOU" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMFOU" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"RUEFOU" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"POSFOU" VARCHAR2(5 CHAR), 
	"VILFOU" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	"CONFOU" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"SATISF" NUMBER(2)
);

-- -- Permet de voir qu'un VARCHAR2 occupe uniquement l'espace en fonction de la donn�e ins�r�e
-- INSERT INTO PAPYRUS.FOURNISSEUR (NUMFOU,NOMFOU,RUEFOU,POSFOU,VILFOU,CONFOU,SATISF) 
-- VALUES (120,'GROBRIGAN','20 rue du papier','92200','Papercity','Georges',8);
-- SELECT VSIZE(NOMFOU) FROM FOURNISSEUR;  --  -> 9 et non 30


CREATE TABLE "COMMANDE" (	
    "ID_COMMANDE" NUMBER(10) NOT NULL ENABLE,
	"ID_FOURNISSEUR" NUMBER(10) NOT NULL ENABLE,
	"NUMCOM" NUMBER(10,0) NOT NULL ENABLE, 
	"OBSCOM" VARCHAR2(25 CHAR),
    "DATECOM" DATE DEFAULT SYSDATE
);

CREATE TABLE "VENTE" (	
    "ID_VENTE" NUMBER(10) NOT NULL ENABLE,
    "ID_PRODUIT" NUMBER(10) NOT NULL ENABLE,
	"ID_FOURNISSEUR" NUMBER(10) NOT NULL ENABLE,
	"DELLIV" NUMBER(6,0) NOT NULL ENABLE, 
	"QTE" NUMBER(6,0), 
	"PRIX" NUMBER(6,2) NOT NULL ENABLE
);

CREATE TABLE "LIGCOM"(	
    "ID_LIGCOM" NUMBER(10) NOT NULL ENABLE,
	"ID_PRODUIT" NUMBER(10) NOT NULL ENABLE,
    "ID_COMMANDE" NUMBER(10) NOT NULL ENABLE, 
	"NUMLIG" SMALLINT NOT NULL ENABLE,
	"QTECDE" SMALLINT NOT NULL ENABLE, 
	"PRIUNI" SMALLINT NOT NULL ENABLE,
	"QTELIV" NUMBER(10,0),
    "DERLIV" DATE NOT NULL ENABLE
);